// Code generated by pigeon; DO NOT EDIT.

package grammar

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/flowchartsman/aql/parser/ast"
)

// TODO:
//   - stop removing stars in generated parser and just remove them later. This
//     allows hinting for them instead, and prevents incorrect offsets in pos.
//   - go back to value checking with a visitor. This lets operation errors be
//     listed as messages, which will let parsing proceed, but highlight
//     problems. Also simplifies parser. Will need error method added to
//     MessageVisitor.
//   - add the rule into ParseError message so that otherwise less-than helpful
//     parse errors can simply state what's expected next. Eventually this can
//     be used for autocompletion.
//   - embed >1 parser errors from PEG so all positions can be retrieved (and
//     displayed)
//   - rename node types to line up AST more with convention (like expression,
//     operation, etc)
//   - attach position to all ast nodes
//   - comments

// ParseError is the exported error type for parsing errors with detailed information as to where they occurred
type ParseError struct {
	Position ast.Pos  `json:"position"`
	Expected []string `json:"expected"`
	Msg      string   `json:"message"`
	List     []error
}

// helper method to exfiltrate pigeon's generated error type as a type that conforms to PositionErr
func GetParseError(err error) *ParseError {
	switch ev := err.(type) {
	case errList:
		if pe, ok := ev[0].(*parserError); ok {
			toklen := 1
			if te, ok := pe.Inner.(*tokenError); ok {
				toklen = te.length
			}
			return &ParseError{
				Position: ast.Pos{
					Line:   pe.pos.line,
					Col:    pe.pos.col,
					Offset: pe.pos.offset,
					Len:    toklen,
				},
				Msg:      pe.Inner.Error(),
				Expected: pe.expected,
			}
		}
	}
	return &ParseError{
		Position: ast.Pos{Offset: -1},
		Msg:      err.Error(),
	}
}

// Error Conforms to Error
func (p *ParseError) Error() string {
	return fmt.Sprintf("%d:%d(%d): %s", p.Position.Line, p.Position.Col, p.Position.Offset, p.Msg)
}

// Message is the raw message of the string
func (p *ParseError) Message() string {
	return p.Msg
}

// Pos conforms to Positioned
func (p *ParseError) Pos() ast.Pos {
	return p.Position
}

// helper to create an ast.Pos from c
func getpos(c *current) ast.Pos {
	return ast.Pos{
		Line:   c.pos.line,
		Col:    c.pos.col,
		Offset: c.pos.offset,
		Len:    utf8.RuneCount(c.text),
	}
}

type tokenError struct {
	err    error
	length int
}

func (t *tokenError) Error() string {
	return t.err.Error()
}

func tokErr(pos ast.Pos, err error) *tokenError {
	return &tokenError{
		err:    err,
		length: pos.Len,
	}
}

func tokErrf(pos ast.Pos, msg string, v ...any) *tokenError {
	return &tokenError{
		err:    fmt.Errorf(msg, v...),
		length: pos.Len,
	}
}

// pigeon helper method, sometimes you gotta do what you gotta do
func toAny(v any) []any {
	if v == nil {
		return nil
	}
	return v.([]any)
}

// helper method to get individual tokens from their rule index
func getTokens(first, rest any, idx int) []string {
	out := []string{first.(string)}
	restSl := toAny(rest)
	for _, v := range restSl {
		expr := toAny(v)
		out = append(out, expr[idx].(string))
	}
	return out
}

// helper method to get label as string value
func toString(label any) (string, error) {
	var sb strings.Builder
	value := label.([]any)
	for _, i := range value {
		if i == nil {
			continue
		}
		switch b := i.(type) {
		case []byte:
			sb.WriteByte(b[0])
		case string:
			sb.WriteString(b)
		case []any:
			s, err := toString(i)
			if err != nil {
				return "", err
			}
			sb.WriteString(s)
		default:
			return "", fmt.Errorf("unexpected type [%T] found in label interfaces: %+v", i, i)
		}
	}
	return sb.String(), nil
}

// helper methods to remove legacy star syntax
func removeStars(ss []string) []string {
	for {
		i := findStarIdx(ss)
		if i < 0 {
			break
		}
		ss = append(ss[:i], ss[i+1:]...)
	}
	return ss
}

func findStarIdx(ss []string) int {
	for i, s := range ss {
		if s == "*" {
			return i
		}
	}
	return -1
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 183, col: 1, offset: 4285},
			expr: &actionExpr{
				pos: position{line: 183, col: 10, offset: 4294},
				run: (*parser).callonStart1,
				expr: &seqExpr{
					pos: position{line: 183, col: 10, offset: 4294},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 183, col: 10, offset: 4294},
							label: "query",
							expr: &ruleRefExpr{
								pos:  position{line: 183, col: 16, offset: 4300},
								name: "Query",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 183, col: 22, offset: 4306},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Query",
			pos:  position{line: 187, col: 1, offset: 4337},
			expr: &actionExpr{
				pos: position{line: 187, col: 10, offset: 4346},
				run: (*parser).callonQuery1,
				expr: &seqExpr{
					pos: position{line: 187, col: 10, offset: 4346},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 187, col: 10, offset: 4346},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 187, col: 12, offset: 4348},
							label: "clause",
							expr: &ruleRefExpr{
								pos:  position{line: 187, col: 19, offset: 4355},
								name: "OrClause",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 187, col: 28, offset: 4364},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "OrClause",
			pos:  position{line: 195, col: 1, offset: 4414},
			expr: &choiceExpr{
				pos: position{line: 195, col: 13, offset: 4426},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 195, col: 13, offset: 4426},
						run: (*parser).callonOrClause2,
						expr: &seqExpr{
							pos: position{line: 195, col: 13, offset: 4426},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 195, col: 13, offset: 4426},
									label: "lhs",
									expr: &ruleRefExpr{
										pos:  position{line: 195, col: 17, offset: 4430},
										name: "AndClause",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 195, col: 27, offset: 4440},
									name: "space",
								},
								&ruleRefExpr{
									pos:  position{line: 195, col: 33, offset: 4446},
									name: "logicalOR",
								},
								&ruleRefExpr{
									pos:  position{line: 195, col: 43, offset: 4456},
									name: "space",
								},
								&labeledExpr{
									pos:   position{line: 195, col: 49, offset: 4462},
									label: "rhs",
									expr: &ruleRefExpr{
										pos:  position{line: 195, col: 53, offset: 4466},
										name: "OrClause",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 200, col: 5, offset: 4578},
						name: "AndClause",
					},
				},
			},
		},
		{
			name: "AndClause",
			pos:  position{line: 202, col: 1, offset: 4589},
			expr: &choiceExpr{
				pos: position{line: 202, col: 14, offset: 4602},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 202, col: 14, offset: 4602},
						run: (*parser).callonAndClause2,
						expr: &seqExpr{
							pos: position{line: 202, col: 14, offset: 4602},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 202, col: 14, offset: 4602},
									label: "lhs",
									expr: &ruleRefExpr{
										pos:  position{line: 202, col: 18, offset: 4606},
										name: "NotClause",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 202, col: 28, offset: 4616},
									name: "space",
								},
								&ruleRefExpr{
									pos:  position{line: 202, col: 34, offset: 4622},
									name: "logicalAND",
								},
								&ruleRefExpr{
									pos:  position{line: 202, col: 45, offset: 4633},
									name: "space",
								},
								&labeledExpr{
									pos:   position{line: 202, col: 51, offset: 4639},
									label: "rhs",
									expr: &ruleRefExpr{
										pos:  position{line: 202, col: 55, offset: 4643},
										name: "AndClause",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 207, col: 5, offset: 4757},
						name: "NotClause",
					},
				},
			},
		},
		{
			name: "NotClause",
			pos:  position{line: 209, col: 1, offset: 4768},
			expr: &choiceExpr{
				pos: position{line: 209, col: 14, offset: 4781},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 209, col: 14, offset: 4781},
						run: (*parser).callonNotClause2,
						expr: &seqExpr{
							pos: position{line: 209, col: 14, offset: 4781},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 209, col: 14, offset: 4781},
									name: "logicalNOT",
								},
								&labeledExpr{
									pos:   position{line: 209, col: 25, offset: 4792},
									label: "cmp",
									expr: &ruleRefExpr{
										pos:  position{line: 209, col: 29, offset: 4796},
										name: "Comparison",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 213, col: 5, offset: 4880},
						name: "Comparison",
					},
				},
			},
		},
		{
			name: "Comparison",
			pos:  position{line: 216, col: 1, offset: 4929},
			expr: &choiceExpr{
				pos: position{line: 216, col: 15, offset: 4943},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 216, col: 15, offset: 4943},
						run: (*parser).callonComparison2,
						expr: &seqExpr{
							pos: position{line: 216, col: 15, offset: 4943},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 216, col: 15, offset: 4943},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 216, col: 19, offset: 4947},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 216, col: 21, offset: 4949},
									label: "query",
									expr: &ruleRefExpr{
										pos:  position{line: 216, col: 27, offset: 4955},
										name: "OrClause",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 216, col: 36, offset: 4964},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 216, col: 38, offset: 4966},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 218, col: 5, offset: 4997},
						run: (*parser).callonComparison10,
						expr: &seqExpr{
							pos: position{line: 218, col: 5, offset: 4997},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 218, col: 5, offset: 4997},
									label: "field",
									expr: &ruleRefExpr{
										pos:  position{line: 218, col: 11, offset: 5003},
										name: "Field",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 218, col: 17, offset: 5009},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 218, col: 19, offset: 5011},
									val:        ":",
									ignoreCase: false,
									want:       "\":\"",
								},
								&ruleRefExpr{
									pos:  position{line: 218, col: 23, offset: 5015},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 218, col: 25, offset: 5017},
									label: "operation",
									expr: &ruleRefExpr{
										pos:  position{line: 218, col: 35, offset: 5027},
										name: "opNoArgs",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 233, col: 6, offset: 5352},
						run: (*parser).callonComparison19,
						expr: &seqExpr{
							pos: position{line: 233, col: 6, offset: 5352},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 233, col: 6, offset: 5352},
									label: "field",
									expr: &ruleRefExpr{
										pos:  position{line: 233, col: 12, offset: 5358},
										name: "Field",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 233, col: 18, offset: 5364},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 233, col: 20, offset: 5366},
									val:        ":",
									ignoreCase: false,
									want:       "\":\"",
								},
								&ruleRefExpr{
									pos:  position{line: 233, col: 24, offset: 5370},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 233, col: 26, offset: 5372},
									label: "operation",
									expr: &zeroOrOneExpr{
										pos: position{line: 233, col: 36, offset: 5382},
										expr: &ruleRefExpr{
											pos:  position{line: 233, col: 36, offset: 5382},
											name: "opComp",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 233, col: 44, offset: 5390},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 233, col: 46, offset: 5392},
									label: "values",
									expr: &ruleRefExpr{
										pos:  position{line: 233, col: 53, offset: 5399},
										name: "ValueList",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 254, col: 1, offset: 5793},
			expr: &actionExpr{
				pos: position{line: 254, col: 10, offset: 5802},
				run: (*parser).callonField1,
				expr: &labeledExpr{
					pos:   position{line: 254, col: 10, offset: 5802},
					label: "pieces",
					expr: &seqExpr{
						pos: position{line: 254, col: 18, offset: 5810},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 254, col: 18, offset: 5810},
								name: "FieldPiece",
							},
							&zeroOrMoreExpr{
								pos: position{line: 254, col: 29, offset: 5821},
								expr: &seqExpr{
									pos: position{line: 254, col: 30, offset: 5822},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 254, col: 30, offset: 5822},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&ruleRefExpr{
											pos:  position{line: 254, col: 34, offset: 5826},
											name: "FieldPiece",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FieldPiece",
			pos:  position{line: 270, col: 1, offset: 6239},
			expr: &choiceExpr{
				pos: position{line: 270, col: 15, offset: 6253},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 270, col: 15, offset: 6253},
						name: "QuotedFieldPiece",
					},
					&ruleRefExpr{
						pos:  position{line: 270, col: 34, offset: 6272},
						name: "UnquotedFieldPiece",
					},
					&ruleRefExpr{
						pos:  position{line: 270, col: 55, offset: 6293},
						name: "Star",
					},
				},
			},
		},
		{
			name: "UnquotedFieldPiece",
			pos:  position{line: 272, col: 1, offset: 6299},
			expr: &actionExpr{
				pos: position{line: 272, col: 23, offset: 6321},
				run: (*parser).callonUnquotedFieldPiece1,
				expr: &oneOrMoreExpr{
					pos: position{line: 272, col: 23, offset: 6321},
					expr: &charClassMatcher{
						pos:        position{line: 272, col: 23, offset: 6321},
						val:        "[a-z0-9_-]i",
						chars:      []rune{'_', '-'},
						ranges:     []rune{'a', 'z', '0', '9'},
						ignoreCase: true,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "QuotedFieldPiece",
			pos:  position{line: 276, col: 1, offset: 6370},
			expr: &actionExpr{
				pos: position{line: 276, col: 21, offset: 6390},
				run: (*parser).callonQuotedFieldPiece1,
				expr: &labeledExpr{
					pos:   position{line: 276, col: 21, offset: 6390},
					label: "qv",
					expr: &ruleRefExpr{
						pos:  position{line: 276, col: 24, offset: 6393},
						name: "QuotedValue",
					},
				},
			},
		},
		{
			name: "Star",
			pos:  position{line: 282, col: 1, offset: 6551},
			expr: &actionExpr{
				pos: position{line: 282, col: 9, offset: 6559},
				run: (*parser).callonStar1,
				expr: &litMatcher{
					pos:        position{line: 282, col: 9, offset: 6559},
					val:        "*",
					ignoreCase: false,
					want:       "\"*\"",
				},
			},
		},
		{
			name: "ValueList",
			pos:  position{line: 291, col: 1, offset: 6677},
			expr: &choiceExpr{
				pos: position{line: 291, col: 14, offset: 6690},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 291, col: 14, offset: 6690},
						run: (*parser).callonValueList2,
						expr: &seqExpr{
							pos: position{line: 291, col: 14, offset: 6690},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 291, col: 14, offset: 6690},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 291, col: 17, offset: 6693},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 291, col: 19, offset: 6695},
									label: "first",
									expr: &ruleRefExpr{
										pos:  position{line: 291, col: 25, offset: 6701},
										name: "Value",
									},
								},
								&labeledExpr{
									pos:   position{line: 291, col: 31, offset: 6707},
									label: "rest",
									expr: &zeroOrMoreExpr{
										pos: position{line: 291, col: 36, offset: 6712},
										expr: &seqExpr{
											pos: position{line: 291, col: 38, offset: 6714},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 291, col: 38, offset: 6714},
													name: "_",
												},
												&litMatcher{
													pos:        position{line: 291, col: 40, offset: 6716},
													val:        ",",
													ignoreCase: false,
													want:       "\",\"",
												},
												&ruleRefExpr{
													pos:  position{line: 291, col: 44, offset: 6720},
													name: "_",
												},
												&ruleRefExpr{
													pos:  position{line: 291, col: 46, offset: 6722},
													name: "Value",
												},
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 291, col: 55, offset: 6731},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 291, col: 57, offset: 6733},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 302, col: 5, offset: 7036},
						run: (*parser).callonValueList17,
						expr: &labeledExpr{
							pos:   position{line: 302, col: 5, offset: 7036},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 302, col: 11, offset: 7042},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 306, col: 1, offset: 7096},
			expr: &choiceExpr{
				pos: position{line: 306, col: 10, offset: 7105},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 306, col: 10, offset: 7105},
						run: (*parser).callonValue2,
						expr: &labeledExpr{
							pos:   position{line: 306, col: 10, offset: 7105},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 306, col: 15, offset: 7110},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 306, col: 15, offset: 7110},
										name: "QuotedValue",
									},
									&ruleRefExpr{
										pos:  position{line: 306, col: 29, offset: 7124},
										name: "RegexValue",
									},
									&ruleRefExpr{
										pos:  position{line: 306, col: 42, offset: 7137},
										name: "BareValue",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 308, col: 5, offset: 7184},
						run: (*parser).callonValue8,
						expr: &oneOrMoreExpr{
							pos: position{line: 308, col: 5, offset: 7184},
							expr: &charClassMatcher{
								pos:        position{line: 308, col: 5, offset: 7184},
								val:        "[^ \\n\\t\\r]",
								chars:      []rune{' ', '\n', '\t', '\r'},
								ignoreCase: false,
								inverted:   true,
							},
						},
					},
				},
			},
		},
		{
			name: "QuotedValue",
			pos:  position{line: 319, col: 1, offset: 7446},
			expr: &recoveryExpr{
				pos: position{line: 319, col: 16, offset: 7461},
				expr: &actionExpr{
					pos: position{line: 319, col: 16, offset: 7461},
					run: (*parser).callonQuotedValue2,
					expr: &seqExpr{
						pos: position{line: 319, col: 16, offset: 7461},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 319, col: 16, offset: 7461},
								val:        "\"",
								ignoreCase: false,
								want:       "\"\\\"\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 319, col: 20, offset: 7465},
								expr: &choiceExpr{
									pos: position{line: 319, col: 22, offset: 7467},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 319, col: 22, offset: 7467},
											exprs: []interface{}{
												&notExpr{
													pos: position{line: 319, col: 22, offset: 7467},
													expr: &ruleRefExpr{
														pos:  position{line: 319, col: 23, offset: 7468},
														name: "EscapedChar",
													},
												},
												&anyMatcher{
													line: 319, col: 35, offset: 7480,
												},
											},
										},
										&seqExpr{
											pos: position{line: 319, col: 39, offset: 7484},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 319, col: 39, offset: 7484},
													val:        "\\",
													ignoreCase: false,
													want:       "\"\\\\\"",
												},
												&ruleRefExpr{
													pos:  position{line: 319, col: 44, offset: 7489},
													name: "EscapeSequence",
												},
											},
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 319, col: 62, offset: 7507},
								name: "EndingQuote",
							},
						},
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 326, col: 20, offset: 7737},
					name: "ErrUntermStr",
				},
				failureLabel: []string{
					"errUntermStr",
				},
			},
		},
		{
			name: "EndingQuote",
			pos:  position{line: 328, col: 1, offset: 7751},
			expr: &choiceExpr{
				pos: position{line: 328, col: 16, offset: 7766},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 328, col: 16, offset: 7766},
						val:        "\"",
						ignoreCase: false,
						want:       "\"\\\"\"",
					},
					&throwExpr{
						pos:   position{line: 328, col: 22, offset: 7772},
						label: "errUntermStr",
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 330, col: 1, offset: 7789},
			expr: &charClassMatcher{
				pos:        position{line: 330, col: 16, offset: 7804},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 332, col: 1, offset: 7820},
			expr: &choiceExpr{
				pos: position{line: 332, col: 19, offset: 7838},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 332, col: 19, offset: 7838},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 332, col: 38, offset: 7857},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 334, col: 1, offset: 7872},
			expr: &charClassMatcher{
				pos:        position{line: 334, col: 21, offset: 7892},
				val:        "[\"\\\\bfnrt]",
				chars:      []rune{'"', '\\', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 336, col: 1, offset: 7904},
			expr: &seqExpr{
				pos: position{line: 336, col: 18, offset: 7921},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 336, col: 18, offset: 7921},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 336, col: 22, offset: 7925},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 336, col: 31, offset: 7934},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 336, col: 40, offset: 7943},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 336, col: 49, offset: 7952},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 338, col: 1, offset: 7962},
			expr: &charClassMatcher{
				pos:        position{line: 338, col: 13, offset: 7974},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "ValueChars",
			pos:  position{line: 340, col: 1, offset: 7985},
			expr: &charClassMatcher{
				pos:        position{line: 340, col: 15, offset: 7999},
				val:        "[a-zA-Z0-9 !]",
				chars:      []rune{' ', '!'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "RegexValue",
			pos:  position{line: 342, col: 1, offset: 8014},
			expr: &recoveryExpr{
				pos: position{line: 342, col: 15, offset: 8028},
				expr: &actionExpr{
					pos: position{line: 342, col: 15, offset: 8028},
					run: (*parser).callonRegexValue2,
					expr: &seqExpr{
						pos: position{line: 342, col: 15, offset: 8028},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 342, col: 15, offset: 8028},
								val:        "/",
								ignoreCase: false,
								want:       "\"/\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 342, col: 19, offset: 8032},
								expr: &ruleRefExpr{
									pos:  position{line: 342, col: 19, offset: 8032},
									name: "RegexChar",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 342, col: 30, offset: 8043},
								name: "EndingSlash",
							},
						},
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 350, col: 22, offset: 8294},
					name: "ErrUntermRegex",
				},
				failureLabel: []string{
					"errUntermRegex",
				},
			},
		},
		{
			name: "RegexChar",
			pos:  position{line: 351, col: 1, offset: 8309},
			expr: &choiceExpr{
				pos: position{line: 351, col: 14, offset: 8322},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 351, col: 14, offset: 8322},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 351, col: 14, offset: 8322},
								expr: &choiceExpr{
									pos: position{line: 351, col: 17, offset: 8325},
									alternatives: []interface{}{
										&litMatcher{
											pos:        position{line: 351, col: 17, offset: 8325},
											val:        "/",
											ignoreCase: false,
											want:       "\"/\"",
										},
										&litMatcher{
											pos:        position{line: 351, col: 23, offset: 8331},
											val:        "\\",
											ignoreCase: false,
											want:       "\"\\\\\"",
										},
										&ruleRefExpr{
											pos:  position{line: 351, col: 30, offset: 8338},
											name: "EOL",
										},
									},
								},
							},
							&anyMatcher{
								line: 351, col: 35, offset: 8343,
							},
						},
					},
					&seqExpr{
						pos: position{line: 351, col: 39, offset: 8347},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 351, col: 39, offset: 8347},
								val:        "\\",
								ignoreCase: false,
								want:       "\"\\\\\"",
							},
							&ruleRefExpr{
								pos:  position{line: 351, col: 44, offset: 8352},
								name: "RegexEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "RegexEscape",
			pos:  position{line: 352, col: 1, offset: 8364},
			expr: &seqExpr{
				pos: position{line: 352, col: 16, offset: 8379},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 352, col: 16, offset: 8379},
						expr: &choiceExpr{
							pos: position{line: 352, col: 18, offset: 8381},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 352, col: 18, offset: 8381},
									name: "EOL",
								},
								&ruleRefExpr{
									pos:  position{line: 352, col: 24, offset: 8387},
									name: "EOF",
								},
							},
						},
					},
					&anyMatcher{
						line: 352, col: 30, offset: 8393,
					},
				},
			},
		},
		{
			name: "EndingSlash",
			pos:  position{line: 354, col: 1, offset: 8396},
			expr: &choiceExpr{
				pos: position{line: 354, col: 16, offset: 8411},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 354, col: 16, offset: 8411},
						val:        "/",
						ignoreCase: false,
						want:       "\"/\"",
					},
					&throwExpr{
						pos:   position{line: 354, col: 22, offset: 8417},
						label: "errUntermRegex",
					},
				},
			},
		},
		{
			name: "BareValue",
			pos:  position{line: 358, col: 1, offset: 8535},
			expr: &choiceExpr{
				pos: position{line: 358, col: 15, offset: 8549},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 358, col: 15, offset: 8549},
						name: "Timestamp",
					},
					&ruleRefExpr{
						pos:  position{line: 359, col: 15, offset: 8573},
						name: "IPValue",
					},
					&ruleRefExpr{
						pos:  position{line: 360, col: 15, offset: 8595},
						name: "FloatValue",
					},
					&ruleRefExpr{
						pos:  position{line: 361, col: 15, offset: 8620},
						name: "IntValue",
					},
					&ruleRefExpr{
						pos:  position{line: 362, col: 15, offset: 8643},
						name: "BoolValue",
					},
				},
			},
		},
		{
			name: "BoolValue",
			pos:  position{line: 365, col: 1, offset: 8655},
			expr: &actionExpr{
				pos: position{line: 365, col: 14, offset: 8668},
				run: (*parser).callonBoolValue1,
				expr: &choiceExpr{
					pos: position{line: 365, col: 15, offset: 8669},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 365, col: 15, offset: 8669},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
						&litMatcher{
							pos:        position{line: 365, col: 25, offset: 8679},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
				},
			},
		},
		{
			name: "FloatValue",
			pos:  position{line: 369, col: 1, offset: 8736},
			expr: &actionExpr{
				pos: position{line: 369, col: 15, offset: 8750},
				run: (*parser).callonFloatValue1,
				expr: &seqExpr{
					pos: position{line: 369, col: 15, offset: 8750},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 369, col: 15, offset: 8750},
							expr: &litMatcher{
								pos:        position{line: 369, col: 15, offset: 8750},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 369, col: 20, offset: 8755},
							expr: &charClassMatcher{
								pos:        position{line: 369, col: 20, offset: 8755},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&litMatcher{
							pos:        position{line: 369, col: 27, offset: 8762},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 369, col: 31, offset: 8766},
							expr: &charClassMatcher{
								pos:        position{line: 369, col: 31, offset: 8766},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "IntValue",
			pos:  position{line: 378, col: 1, offset: 8934},
			expr: &actionExpr{
				pos: position{line: 378, col: 13, offset: 8946},
				run: (*parser).callonIntValue1,
				expr: &seqExpr{
					pos: position{line: 378, col: 13, offset: 8946},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 378, col: 13, offset: 8946},
							expr: &litMatcher{
								pos:        position{line: 378, col: 13, offset: 8946},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 378, col: 18, offset: 8951},
							expr: &charClassMatcher{
								pos:        position{line: 378, col: 18, offset: 8951},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "IPValue",
			pos:  position{line: 383, col: 1, offset: 9008},
			expr: &actionExpr{
				pos: position{line: 383, col: 12, offset: 9019},
				run: (*parser).callonIPValue1,
				expr: &seqExpr{
					pos: position{line: 383, col: 12, offset: 9019},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 383, col: 12, offset: 9019},
							name: "Octet",
						},
						&litMatcher{
							pos:        position{line: 383, col: 18, offset: 9025},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&ruleRefExpr{
							pos:  position{line: 383, col: 22, offset: 9029},
							name: "Octet",
						},
						&litMatcher{
							pos:        position{line: 383, col: 28, offset: 9035},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&ruleRefExpr{
							pos:  position{line: 383, col: 32, offset: 9039},
							name: "Octet",
						},
						&litMatcher{
							pos:        position{line: 383, col: 38, offset: 9045},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&ruleRefExpr{
							pos:  position{line: 383, col: 42, offset: 9049},
							name: "Octet",
						},
						&zeroOrOneExpr{
							pos: position{line: 383, col: 48, offset: 9055},
							expr: &ruleRefExpr{
								pos:  position{line: 383, col: 48, offset: 9055},
								name: "CIDRBlock",
							},
						},
					},
				},
			},
		},
		{
			name: "Octet",
			pos:  position{line: 392, col: 1, offset: 9217},
			expr: &seqExpr{
				pos: position{line: 392, col: 10, offset: 9226},
				exprs: []interface{}{
					&charClassMatcher{
						pos:        position{line: 392, col: 10, offset: 9226},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&zeroOrOneExpr{
						pos: position{line: 392, col: 15, offset: 9231},
						expr: &charClassMatcher{
							pos:        position{line: 392, col: 15, offset: 9231},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 392, col: 21, offset: 9237},
						expr: &charClassMatcher{
							pos:        position{line: 392, col: 21, offset: 9237},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "CIDRBlock",
			pos:  position{line: 394, col: 1, offset: 9245},
			expr: &seqExpr{
				pos: position{line: 394, col: 14, offset: 9258},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 394, col: 14, offset: 9258},
						val:        "/",
						ignoreCase: false,
						want:       "\"/\"",
					},
					&charClassMatcher{
						pos:        position{line: 394, col: 18, offset: 9262},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&zeroOrOneExpr{
						pos: position{line: 394, col: 23, offset: 9267},
						expr: &charClassMatcher{
							pos:        position{line: 394, col: 23, offset: 9267},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Timestamp",
			pos:  position{line: 397, col: 1, offset: 9287},
			expr: &actionExpr{
				pos: position{line: 397, col: 14, offset: 9300},
				run: (*parser).callonTimestamp1,
				expr: &choiceExpr{
					pos: position{line: 397, col: 15, offset: 9301},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 397, col: 15, offset: 9301},
							name: "dateTime",
						},
						&ruleRefExpr{
							pos:  position{line: 397, col: 26, offset: 9312},
							name: "fullDate",
						},
					},
				},
			},
		},
		{
			name: "dateTime",
			pos:  position{line: 407, col: 1, offset: 9493},
			expr: &seqExpr{
				pos: position{line: 407, col: 13, offset: 9505},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 407, col: 13, offset: 9505},
						name: "fullDate",
					},
					&choiceExpr{
						pos: position{line: 407, col: 23, offset: 9515},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 407, col: 23, offset: 9515},
								val:        "t",
								ignoreCase: true,
								want:       "\"T\"i",
							},
							&litMatcher{
								pos:        position{line: 407, col: 30, offset: 9522},
								val:        " ",
								ignoreCase: false,
								want:       "\" \"",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 407, col: 35, offset: 9527},
						name: "fullTime",
					},
				},
			},
		},
		{
			name: "fullDate",
			pos:  position{line: 408, col: 1, offset: 9536},
			expr: &seqExpr{
				pos: position{line: 408, col: 13, offset: 9548},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 408, col: 13, offset: 9548},
						name: "dateFullyear",
					},
					&litMatcher{
						pos:        position{line: 408, col: 26, offset: 9561},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&ruleRefExpr{
						pos:  position{line: 408, col: 30, offset: 9565},
						name: "dateMonth",
					},
					&litMatcher{
						pos:        position{line: 408, col: 40, offset: 9575},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&ruleRefExpr{
						pos:  position{line: 408, col: 44, offset: 9579},
						name: "dateMday",
					},
				},
			},
		},
		{
			name: "dateFullyear",
			pos:  position{line: 410, col: 1, offset: 9589},
			expr: &ruleRefExpr{
				pos:  position{line: 410, col: 17, offset: 9605},
				name: "Digit4",
			},
		},
		{
			name: "dateMonth",
			pos:  position{line: 411, col: 1, offset: 9612},
			expr: &ruleRefExpr{
				pos:  position{line: 411, col: 14, offset: 9625},
				name: "Digit2",
			},
		},
		{
			name: "dateMday",
			pos:  position{line: 412, col: 1, offset: 9632},
			expr: &ruleRefExpr{
				pos:  position{line: 412, col: 13, offset: 9644},
				name: "Digit2",
			},
		},
		{
			name: "timeHour",
			pos:  position{line: 413, col: 1, offset: 9651},
			expr: &ruleRefExpr{
				pos:  position{line: 413, col: 13, offset: 9663},
				name: "Digit2",
			},
		},
		{
			name: "timeMinute",
			pos:  position{line: 414, col: 1, offset: 9670},
			expr: &ruleRefExpr{
				pos:  position{line: 414, col: 15, offset: 9684},
				name: "Digit2",
			},
		},
		{
			name: "timeSecond",
			pos:  position{line: 415, col: 1, offset: 9691},
			expr: &ruleRefExpr{
				pos:  position{line: 415, col: 15, offset: 9705},
				name: "Digit2",
			},
		},
		{
			name: "timeSecfrac",
			pos:  position{line: 416, col: 1, offset: 9712},
			expr: &seqExpr{
				pos: position{line: 416, col: 16, offset: 9727},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 416, col: 16, offset: 9727},
						val:        ".",
						ignoreCase: false,
						want:       "\".\"",
					},
					&oneOrMoreExpr{
						pos: position{line: 416, col: 20, offset: 9731},
						expr: &charClassMatcher{
							pos:        position{line: 416, col: 20, offset: 9731},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "timeNumoffset",
			pos:  position{line: 417, col: 1, offset: 9738},
			expr: &seqExpr{
				pos: position{line: 417, col: 18, offset: 9755},
				exprs: []interface{}{
					&choiceExpr{
						pos: position{line: 417, col: 19, offset: 9756},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 417, col: 19, offset: 9756},
								val:        "+",
								ignoreCase: false,
								want:       "\"+\"",
							},
							&litMatcher{
								pos:        position{line: 417, col: 25, offset: 9762},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 417, col: 30, offset: 9767},
						name: "timeHour",
					},
					&litMatcher{
						pos:        position{line: 417, col: 39, offset: 9776},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 417, col: 43, offset: 9780},
						name: "timeMinute",
					},
				},
			},
		},
		{
			name: "timeOffset",
			pos:  position{line: 418, col: 1, offset: 9791},
			expr: &choiceExpr{
				pos: position{line: 418, col: 15, offset: 9805},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 418, col: 15, offset: 9805},
						val:        "z",
						ignoreCase: true,
						want:       "\"Z\"i",
					},
					&ruleRefExpr{
						pos:  position{line: 418, col: 22, offset: 9812},
						name: "timeNumoffset",
					},
				},
			},
		},
		{
			name: "partialTime",
			pos:  position{line: 419, col: 1, offset: 9826},
			expr: &seqExpr{
				pos: position{line: 419, col: 16, offset: 9841},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 419, col: 16, offset: 9841},
						name: "timeHour",
					},
					&litMatcher{
						pos:        position{line: 419, col: 25, offset: 9850},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 419, col: 29, offset: 9854},
						name: "timeMinute",
					},
					&litMatcher{
						pos:        position{line: 419, col: 40, offset: 9865},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 419, col: 44, offset: 9869},
						name: "timeSecond",
					},
					&zeroOrOneExpr{
						pos: position{line: 419, col: 55, offset: 9880},
						expr: &ruleRefExpr{
							pos:  position{line: 419, col: 55, offset: 9880},
							name: "timeSecfrac",
						},
					},
				},
			},
		},
		{
			name: "fullTime",
			pos:  position{line: 420, col: 1, offset: 9893},
			expr: &seqExpr{
				pos: position{line: 420, col: 13, offset: 9905},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 420, col: 13, offset: 9905},
						name: "partialTime",
					},
					&ruleRefExpr{
						pos:  position{line: 420, col: 25, offset: 9917},
						name: "timeOffset",
					},
				},
			},
		},
		{
			name: "Digit4",
			pos:  position{line: 421, col: 1, offset: 9928},
			expr: &seqExpr{
				pos: position{line: 421, col: 11, offset: 9938},
				exprs: []interface{}{
					&charClassMatcher{
						pos:        position{line: 421, col: 11, offset: 9938},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 421, col: 16, offset: 9943},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 421, col: 21, offset: 9948},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 421, col: 26, offset: 9953},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Digit2",
			pos:  position{line: 422, col: 1, offset: 9959},
			expr: &seqExpr{
				pos: position{line: 422, col: 11, offset: 9969},
				exprs: []interface{}{
					&charClassMatcher{
						pos:        position{line: 422, col: 11, offset: 9969},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 422, col: 16, offset: 9974},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "logicalOR",
			pos:  position{line: 428, col: 1, offset: 10037},
			expr: &litMatcher{
				pos:        position{line: 428, col: 14, offset: 10050},
				val:        "OR",
				ignoreCase: false,
				want:       "\"OR\"",
			},
		},
		{
			name: "logicalAND",
			pos:  position{line: 430, col: 1, offset: 10056},
			expr: &litMatcher{
				pos:        position{line: 430, col: 15, offset: 10070},
				val:        "AND",
				ignoreCase: false,
				want:       "\"AND\"",
			},
		},
		{
			name: "logicalNOT",
			pos:  position{line: 432, col: 1, offset: 10077},
			expr: &choiceExpr{
				pos: position{line: 432, col: 15, offset: 10091},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 432, col: 15, offset: 10091},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 432, col: 15, offset: 10091},
								val:        "NOT",
								ignoreCase: false,
								want:       "\"NOT\"",
							},
							&ruleRefExpr{
								pos:  position{line: 432, col: 21, offset: 10097},
								name: "space",
							},
						},
					},
					&seqExpr{
						pos: position{line: 432, col: 29, offset: 10105},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 432, col: 29, offset: 10105},
								val:        "!",
								ignoreCase: false,
								want:       "\"!\"",
							},
							&zeroOrOneExpr{
								pos: position{line: 432, col: 33, offset: 10109},
								expr: &ruleRefExpr{
									pos:  position{line: 432, col: 33, offset: 10109},
									name: "space",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "opNoArgs",
			pos:  position{line: 438, col: 1, offset: 10182},
			expr: &actionExpr{
				pos: position{line: 438, col: 13, offset: 10194},
				run: (*parser).callonopNoArgs1,
				expr: &choiceExpr{
					pos: position{line: 438, col: 14, offset: 10195},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 438, col: 14, offset: 10195},
							val:        "exists",
							ignoreCase: false,
							want:       "\"exists\"",
						},
						&litMatcher{
							pos:        position{line: 438, col: 25, offset: 10206},
							val:        "null",
							ignoreCase: false,
							want:       "\"null\"",
						},
					},
				},
			},
		},
		{
			name: "opComp",
			pos:  position{line: 449, col: 1, offset: 10379},
			expr: &actionExpr{
				pos: position{line: 449, col: 11, offset: 10389},
				run: (*parser).callonopComp1,
				expr: &choiceExpr{
					pos: position{line: 449, col: 12, offset: 10390},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 449, col: 12, offset: 10390},
							val:        "><",
							ignoreCase: false,
							want:       "\"><\"",
						},
						&litMatcher{
							pos:        position{line: 449, col: 19, offset: 10397},
							val:        "~",
							ignoreCase: false,
							want:       "\"~\"",
						},
						&seqExpr{
							pos: position{line: 449, col: 25, offset: 10403},
							exprs: []interface{}{
								&charClassMatcher{
									pos:        position{line: 449, col: 25, offset: 10403},
									val:        "[<>]",
									chars:      []rune{'<', '>'},
									ignoreCase: false,
									inverted:   false,
								},
								&zeroOrOneExpr{
									pos: position{line: 449, col: 30, offset: 10408},
									expr: &litMatcher{
										pos:        position{line: 449, col: 30, offset: 10408},
										val:        "=",
										ignoreCase: false,
										want:       "\"=\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 477, col: 1, offset: 10921},
			expr: &zeroOrMoreExpr{
				pos: position{line: 477, col: 19, offset: 10939},
				expr: &charClassMatcher{
					pos:        position{line: 477, col: 19, offset: 10939},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "space",
			pos:  position{line: 479, col: 1, offset: 10951},
			expr: &oneOrMoreExpr{
				pos: position{line: 479, col: 10, offset: 10960},
				expr: &charClassMatcher{
					pos:        position{line: 479, col: 10, offset: 10960},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 481, col: 1, offset: 10972},
			expr: &litMatcher{
				pos:        position{line: 481, col: 8, offset: 10979},
				val:        "\n",
				ignoreCase: false,
				want:       "\"\\n\"",
			},
		},
		{
			name: "EOF",
			pos:  position{line: 483, col: 1, offset: 10985},
			expr: &notExpr{
				pos: position{line: 483, col: 7, offset: 10991},
				expr: &anyMatcher{
					line: 483, col: 8, offset: 10992,
				},
			},
		},
		{
			name: "ErrUntermStr",
			pos:  position{line: 489, col: 1, offset: 11090},
			expr: &stateCodeExpr{
				pos: position{line: 489, col: 17, offset: 11106},
				run: (*parser).callonErrUntermStr1,
			},
		},
		{
			name: "ErrUntermRegex",
			pos:  position{line: 493, col: 1, offset: 11205},
			expr: &stateCodeExpr{
				pos: position{line: 493, col: 19, offset: 11223},
				run: (*parser).callonErrUntermRegex1,
			},
		},
	},
}

func (c *current) onStart1(query interface{}) (interface{}, error) {
	return query, nil
}

func (p *parser) callonStart1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStart1(stack["query"])
}

func (c *current) onQuery1(clause interface{}) (interface{}, error) {
	return clause, nil
}

func (p *parser) callonQuery1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuery1(stack["clause"])
}

func (c *current) onOrClause2(lhs, rhs interface{}) (interface{}, error) {
	return &ast.OrNode{
		Left:  lhs.(ast.Node),
		Right: rhs.(ast.Node),
	}, nil
}

func (p *parser) callonOrClause2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrClause2(stack["lhs"], stack["rhs"])
}

func (c *current) onAndClause2(lhs, rhs interface{}) (interface{}, error) {
	return &ast.AndNode{
		Left:  lhs.(ast.Node),
		Right: rhs.(ast.Node),
	}, nil
}

func (p *parser) callonAndClause2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndClause2(stack["lhs"], stack["rhs"])
}

func (c *current) onNotClause2(cmp interface{}) (interface{}, error) {
	return &ast.NotNode{
		Expr: cmp.(ast.Node),
	}, nil
}

func (p *parser) callonNotClause2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotClause2(stack["cmp"])
}

func (c *current) onComparison2(query interface{}) (interface{}, error) {
	return query, nil
}

func (p *parser) callonComparison2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison2(stack["query"])
}

func (c *current) onComparison10(field, operation interface{}) (interface{}, error) {
	return &ast.ExprNode{
		Op:       operation.(ast.Op),
		Field:    field.([]string),
		Position: getpos(c),
	}, nil
}

func (p *parser) callonComparison10() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison10(stack["field"], stack["operation"])
}

func (c *current) onComparison19(field, operation, values interface{}) (interface{}, error) {
	var opOut ast.Op
	if operation == nil {
		opOut = ast.EQ
	} else {
		opOut = operation.(ast.Op)
	}
	node := &ast.ExprNode{
		Op:       opOut,
		Field:    field.([]string),
		RVals:    values.([]ast.Val),
		Position: getpos(c),
	}
	return node, nil
}

func (p *parser) callonComparison19() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison19(stack["field"], stack["operation"], stack["values"])
}

func (c *current) onField1(pieces interface{}) (interface{}, error) {
	piecesSl := toAny(pieces)
	if len(piecesSl) == 0 {
		return nil, fmt.Errorf("empty field")
	}
	// remove stars for now, they are redundant legacy syntax
	field := []string{piecesSl[0].(string)}
	restSl := toAny(piecesSl[1])
	for _, v := range restSl {
		vSl := toAny(v)
		field = append(field, vSl[1].(string))
	}

	return removeStars(field), nil
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["pieces"])
}

func (c *current) onUnquotedFieldPiece1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonUnquotedFieldPiece1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnquotedFieldPiece1()
}

func (c *current) onQuotedFieldPiece1(qv interface{}) (interface{}, error) {
	// intercept the ast node and just use it as a string for field pieces
	return (qv.(*ast.StringVal).Value()), nil
}

func (p *parser) callonQuotedFieldPiece1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotedFieldPiece1(stack["qv"])
}

func (c *current) onStar1() (interface{}, error) {
	return "*", nil
}

func (p *parser) callonStar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStar1()
}

func (c *current) onValueList2(first, rest interface{}) (interface{}, error) {
	out := []ast.Val{first.(ast.Val)}
	restSl := toAny(rest)
	if len(restSl) == 0 {
		return nil, fmt.Errorf("unnecessary parenthesis for only one value")
	}
	for _, v := range restSl {
		r := toAny(v)
		out = append(out, r[3].(ast.Val))
	}
	return out, nil
}

func (p *parser) callonValueList2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValueList2(stack["first"], stack["rest"])
}

func (c *current) onValueList17(value interface{}) (interface{}, error) {
	return []ast.Val{value.(ast.Val)}, nil
}

func (p *parser) callonValueList17() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValueList17(stack["value"])
}

func (c *current) onValue2(val interface{}) (interface{}, error) {
	return val.(ast.Val), nil
}

func (p *parser) callonValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue2(stack["val"])
}

func (c *current) onValue8() (interface{}, error) {
	if c.text[0] == ')' {
		return nil, fmt.Errorf("unexpected closing parenthesis, expecting values")
	}
	return nil, fmt.Errorf("unknown type of value [%s] -- did you mean %q?", c.text, c.text)
}

func (p *parser) callonValue8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue8()
}

func (c *current) onQuotedValue2() (interface{}, error) {
	pos := getpos(c)
	s, err := strconv.Unquote(string(c.text))
	if err != nil {
		return nil, tokErrf(pos, "invalid string: %s", err)
	}
	return ast.NewStringVal([]byte(s), pos)
}

func (p *parser) callonQuotedValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotedValue2()
}

func (c *current) onRegexValue2() (interface{}, error) {
	pos := getpos(c)
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	val, err := ast.NewRegexpVal(c.text, pos)
	if err != nil {
		return nil, tokErr(pos, err)
	}
	return val, nil
}

func (p *parser) callonRegexValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegexValue2()
}

func (c *current) onBoolValue1() (interface{}, error) {
	return ast.NewBoolVal(c.text, getpos(c))
}

func (p *parser) callonBoolValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolValue1()
}

func (c *current) onFloatValue1() (interface{}, error) {
	pos := getpos(c)
	val, err := ast.NewFloatVal(c.text, getpos(c))
	if err != nil {
		return nil, tokErr(pos, err)
	}
	return val, nil
}

func (p *parser) callonFloatValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloatValue1()
}

func (c *current) onIntValue1() (interface{}, error) {
	return ast.NewIntVal(c.text, getpos(c))
}

func (p *parser) callonIntValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntValue1()
}

func (c *current) onIPValue1() (interface{}, error) {
	pos := getpos(c)
	val, err := ast.NewNetVal(c.text, pos)
	if err != nil {
		return nil, tokErr(pos, err)
	}
	return val, nil
}

func (p *parser) callonIPValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIPValue1()
}

func (c *current) onTimestamp1() (interface{}, error) {
	pos := getpos(c)
	val, err := ast.NewTimeVal(c.text, pos)
	if err != nil {
		return nil, tokErr(pos, err)
	}
	return val, nil
}

func (p *parser) callonTimestamp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimestamp1()
}

func (c *current) onopNoArgs1() (interface{}, error) {
	var opOut ast.Op
	switch string(c.text) {
	case "exists":
		opOut = ast.EXS
	case "null":
		opOut = ast.NUL
	}
	return opOut, nil
}

func (p *parser) callonopNoArgs1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onopNoArgs1()
}

func (c *current) onopComp1() (interface{}, error) {
	var opOut ast.Op
	switch string(c.text) {
	case "><":
		opOut = ast.BET
	case "~":
		opOut = ast.SIM
	case "<":
		opOut = ast.LT
	case "<=":
		opOut = ast.LTE
	case ">":
		opOut = ast.GT
	case ">=":
		opOut = ast.GTE
	}
	return opOut, nil
}

func (p *parser) callonopComp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onopComp1()
}

func (c *current) onErrUntermStr1() error {
	return errors.New(`unterminated string, check for missing closing ["] or unescaped [\]`)
}

func (p *parser) callonErrUntermStr1() error {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onErrUntermStr1()
}

func (c *current) onErrUntermRegex1() error {
	return errors.New("unterminated regular expression, did you forget a closing '/'?")
}

func (p *parser) callonErrUntermRegex1() error {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onErrUntermRegex1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
